language: go

before_install:
    - go get -v github.com/Masterminds/glide
    - cd $GOPATH/src/github.com/Masterminds/glide && git checkout e73500c735917e39a8b782e0632418ab70250341 && go install && cd -
    - glide install
    - sudo apt-get update
    - sudo apt-get install docker-ce

script:
    - glide install
    - go build -o ./bin/anzu-chain *.go
    - export D_TAG=latest
    - if [ $TRAVIS_BRANCH != 'master' ]; then export D_TAG=`echo $TRAVIS_BRANCH | sed -e 's/\//-/g'`; fi
    - docker build ./ --tag=${D_USER}/anzu-chain:$D_TAG
    - docker login -u $D_USER -p $D_PASS
    - docker push ${D_USER}/anzu-chain:$D_TAG
 
