version: "3"

services:
    shima-chain-1:
        container_name: shima1
        image: invincibleman/shima-chain
        ports:
            - 8081:8080
        depends_on:
            - ena
        environment:
            ANZU_MINORACCOUNTID: shima1
            ANZU_REDISNODECOUNT: 4
            ANZU_REDISHOST: ena
            ANZU_REDISPORT: 6379

    shima-chain-2:
        container_name: shima2
        image: invincibleman/shima-chain
        ports:
            - 8082:8080
        depends_on:
            - ena
        environment:
            ANZU_MINORACCOUNTID: shima2
            ANZU_REDISNODECOUNT: 4
            ANZU_REDISHOST: ena
            ANZU_REDISPORT: 6379

    shima-chain-3:
        container_name: shima3
        image: invincibleman/shima-chain
        ports:
            - 8083:8080
        depends_on:
            - ena
        environment:
            ANZU_MINORACCOUNTID: shima3
            ANZU_REDISNODECOUNT: 4
            ANZU_REDISHOST: ena
            ANZU_REDISPORT: 6379

    shima-chain-4:
        container_name: shima4
        image: invincibleman/shima-chain
        ports:
            - 8084:8080
        depends_on:
            - ena
        environment:
            ANZU_MINORACCOUNTID: shima4
            ANZU_REDISNODECOUNT: 4
            ANZU_REDISHOST: ena
            ANZU_REDISPORT: 6379

    ena:
        container_name: ena
        ports:
            - 6379:6379
        image: invincibleman/ena

