version: "3"

services:
    anzu-chain-1:
        container_name: anzu1
        image: invincibleman/anzu-chain
        ports:
            - 8081:8080
        depends_on:
            - kirarin-shower
        environment:
            ANZU_REDISNODECOUNT: 4
            ANZU_REDISHOST: kirarin-shower
            ANZU_REDISPORT: 6379

    anzu-chain-2:
        container_name: anzu2
        image: invincibleman/anzu-chain
        ports:
            - 8082:8080
        depends_on:
            - kirarin-shower
        environment:
            ANZU_REDISNODECOUNT: 4
            ANZU_REDISHOST: kirarin-shower
            ANZU_REDISPORT: 6379

    anzu-chain-3:
        container_name: anzu3
        image: invincibleman/anzu-chain
        ports:
            - 8083:8080
        depends_on:
            - kirarin-shower
        environment:
            ANZU_REDISNODECOUNT: 4
            ANZU_REDISHOST: kirarin-shower
            ANZU_REDISPORT: 6379

    anzu-chain-4:
        container_name: anzu4
        image: invincibleman/anzu-chain
        ports:
            - 8084:8080
        depends_on:
            - kirarin-shower
        environment:
            ANZU_REDISNODECOUNT: 4
            ANZU_REDISHOST: kirarin-shower
            ANZU_REDISPORT: 6379

    kirarin-shower:
        container_name: kirarin-shower
        ports:
            - 6379:6379
        image: invincibleman/kirarin-shower

